---
- name: Provision EC2 Instance for Test Server
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: "us-east-1"  # CHANGE TO YOUR REGION
    instance_type: "t2.micro"
    ami_id: "ami-08c40ec9ead489470"  # Ubuntu 22.04 LTS in us-east-1
    key_name: "jenkins-ec2-key"      # You need to create this in AWS EC2 first!
    sec_group: "jenkins-sg"          # You need to create this too!

  tasks:
    - name: Create EC2 Instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "{{ aws_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sec_group }}"
        wait: yes
        name: "Jenkins-Test-Server"
        tags:
          Name: "Jenkins-Test-Server"
          Environment: "Test"
      register: ec2

    - name: Add new instance to host group
      add_host:
        name: "{{ ec2.instances[0].public_ip_address }}"
        groups: test_servers
        ansible_user: "ubuntu"
        ansible_ssh_private_key_file: "/var/lib/jenkins/.ssh/id_rsa"

    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        timeout: 300
