- name: Provision EC2 Test Server
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aws_region: "us-east-1"
    instance_type: "t3.micro"
    ami_id: "ami-052064a798f08f0d3"  # Ensure this AMI exists in your region
    key_name: "new-jenkins-key"      # Ensure this key pair exists in AWS
    sec_group: "jenkins-k8s-sg"          # Ensure this security group exists

  tasks:
    - name: Create EC2 Instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "{{ aws_region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_groups: ["{{ sec_group }}"]
        wait: yes
        count: 1
        tags:  # Use 'tags' instead of 'instance_tags'
          Name: "jenkins-master1"
          Environment: "Test"
      register: ec2

    - name: Print instance public IP
      debug:
        msg: "The new instance public IP is {{ ec2.instances[0].public_ip_address }}"

    - name: Save public IP to file
      copy:
        dest: "ec2_public_ip.txt"
        content: "{{ ec2.instances[0].public_ip_address }}"
